'use client';

/**
 * Copyright (c) 2025 Dario Vucinic - FlowSheet
 * All rights reserved.
 * 
 * This source code is proprietary and confidential.
 * Unauthorized copying, distribution, or use is strictly prohibited.
 */

import React from 'react';
import { Block } from '@/types/block';
import { InlineMath } from 'react-katex';
import ReactMarkdown from 'react-markdown';
import 'katex/dist/katex.min.css';
import { create, all } from 'mathjs';

const math = create(all);

interface PrintViewProps {
    blocks: Block[];
    scope?: Record<string, any>;
}

const PrintView: React.FC<PrintViewProps> = ({ blocks, scope = {} }) => {

    const getFormulaLatex = (content: string) => {
        try {
            const lines = content.split('\n');
            const displayLines = lines.map(line => {
                if (!line.trim()) return '';

                // Basic LaTeX conversion
                let latex = line;
                latex = latex.replace(/([a-zA-Z0-9]+|\([^)]+\))\/([a-zA-Z0-9]+|\([^)]+\))/g, '\\frac{$1}{$2}');
                latex = latex.replace(/\*/g, '\\cdot ').replace(/\^/g, '^');

                // Evaluate if possible
                try {
                    // Prepare scope for mathjs
                    const matrixScope: Record<string, any> = {};
                    for (const [key, value] of Object.entries(scope)) {
                        if (Array.isArray(value)) {
                            matrixScope[key] = math.matrix(value);
                        } else {
                            matrixScope[key] = value;
                        }
                    }

                    const result = math.evaluate(line, matrixScope);

                    // Format result
                    let formattedResult = '';
                    if (typeof result === 'number') {
                        formattedResult = Number.isInteger(result) ? result.toString() : result.toFixed(4);
                    } else if (result && typeof result === 'object') {
                        formattedResult = JSON.stringify(result);
                    } else if (result !== undefined) {
                        formattedResult = result.toString();
                    }

                    // Append result if it's not a simple assignment (e.g. a=5) where result is 5
                    if (formattedResult) {
                        const isAssignment = line.includes('=');
                        const rhs = isAssignment ? line.split('=').pop()?.trim() : line.trim();
                        if (rhs !== formattedResult) {
                            latex += ` = ${formattedResult}`;
                        }
                    }
                } catch (e) {
                    // Ignore evaluation errors in print view
                }

                return `&${latex}`;
            });

            return `\\begin{aligned} ${displayLines.join(' \\\\ ')} \\end{aligned}`;
        } catch (e) {
            return content;
        }
    };

    return (
        <div className="p-8 max-w-4xl mx-auto bg-white min-h-screen">
            <div className="mb-8 border-b pb-4">
                <h1 className="text-3xl font-bold text-slate-900">Engineering Report</h1>
                <p className="text-slate-500">Generated by FlowSheet</p>
                <p className="text-sm text-slate-400 mt-1">{new Date().toLocaleDateString()}</p>
            </div>

            <div className="space-y-8">
                {blocks.map(block => (
                    <div key={block.id} className="break-inside-avoid">
                        {block.type === 'text' && (
                            <div
                                className="prose max-w-none text-slate-800"
                                style={{
                                    color: block.style?.color,
                                    fontSize: block.style?.fontSize,
                                    fontFamily: block.style?.fontFamily,
                                    textAlign: block.style?.textAlign
                                }}
                            >
                                {/* We need to import ReactMarkdown for this to work */}
                                <ReactMarkdown
                                    components={{
                                        p: ({ node, ...props }: any) => <p className="mb-2 last:mb-0" {...props} />,
                                        h1: ({ node, ...props }: any) => <h1 className="text-2xl font-bold mb-2" {...props} />,
                                        h2: ({ node, ...props }: any) => <h2 className="text-xl font-bold mb-2" {...props} />,
                                        h3: ({ node, ...props }: any) => <h3 className="text-lg font-bold mb-2" {...props} />,
                                        ul: ({ node, ...props }: any) => <ul className="list-disc list-inside mb-2" {...props} />,
                                        ol: ({ node, ...props }: any) => <ol className="list-decimal list-inside mb-2" {...props} />,
                                        code: ({ node, ...props }: any) => <code className="bg-slate-100 px-1 py-0.5 rounded text-sm font-mono text-pink-500" {...props} />,
                                    }}
                                >
                                    {(() => {
                                        const content = (block as any).content || '';
                                        const interpolated = content.replace(/\{(\w+)\}/g, (match: string, varName: string) => {
                                            const value = scope[varName];
                                            return value !== undefined ? String(value) : match;
                                        });
                                        return interpolated.replace(/\n/g, '  \n');
                                    })()}
                                </ReactMarkdown>
                            </div>
                        )}

                        {block.type === 'formula' && (
                            <div className="p-4 bg-slate-50 rounded-lg border border-slate-100 flex items-center justify-center my-4">
                                <div className="text-lg">
                                    <InlineMath math={getFormulaLatex((block as any).content)} />
                                </div>
                            </div>
                        )}

                        {block.type === 'table' && (
                            <div className="my-4">
                                <h3 className="text-sm font-semibold text-slate-500 mb-2 uppercase tracking-wider">
                                    Table: {(block as any).variableName || 'Untitled'}
                                </h3>
                                <table className="w-full border-collapse border border-slate-200 text-sm">
                                    <tbody>
                                        {(block as any).content.map((row: any[], i: number) => (
                                            <tr key={i}>
                                                {row.map((cell: any, j: number) => (
                                                    <td key={j} className="border border-slate-200 p-2 text-center text-slate-700">
                                                        {String(cell)}
                                                    </td>
                                                ))}
                                            </tr>
                                        ))}
                                    </tbody>
                                </table>
                            </div>
                        )}

                        {block.type === 'image' && (
                            <div className="my-4 flex justify-center">
                                <img src={(block as any).content} alt="Report Image" className="max-w-full rounded-lg shadow-sm" />
                            </div>
                        )}

                        {block.type === 'script' && (
                            <div className="my-4 font-mono text-sm">
                                <div className="bg-slate-900 text-slate-200 p-4 rounded-t-lg">
                                    <pre className="whitespace-pre-wrap">{(block as any).content}</pre>
                                </div>
                                {(block as any).output && (
                                    <div className="bg-slate-100 text-slate-700 p-4 rounded-b-lg border-x border-b border-slate-200">
                                        <div className="text-xs font-bold text-slate-400 mb-1">OUTPUT</div>
                                        <pre className="whitespace-pre-wrap">{(block as any).output}</pre>
                                    </div>
                                )}
                            </div>
                        )}

                        {block.type === 'cad' && (
                            <div className="my-4 p-8 bg-slate-50 border border-slate-200 rounded-lg flex flex-col items-center justify-center text-slate-400">
                                <div className="text-4xl mb-2">🧊</div>
                                <div className="text-sm font-medium">3D Model</div>
                                <div className="text-xs mt-1">Interactive 3D content not available in print</div>
                            </div>
                        )}

                        {block.type === 'data' && (
                            <div className="my-4">
                                <h3 className="text-sm font-semibold text-slate-500 mb-2 uppercase tracking-wider">
                                    Data: {(block as any).variableName || (block as any).fileName || 'Imported Data'}
                                </h3>
                                {(() => {
                                    const dataBlock = block as any;
                                    const sheetName = dataBlock.selectedSheet;
                                    const sheetData = dataBlock.data && sheetName ? dataBlock.data[sheetName] : null;

                                    if (!sheetData || !Array.isArray(sheetData)) {
                                        return <div className="text-sm text-slate-400 italic">No data available</div>;
                                    }

                                    // Limit to first 50 rows for PDF
                                    const displayData = sheetData.slice(0, 50);

                                    return (
                                        <>
                                            <div className="text-xs text-slate-400 mb-1">
                                                Sheet: {sheetName} ({sheetData.length} rows{sheetData.length > 50 ? ', showing first 50' : ''})
                                            </div>
                                            <table className="w-full border-collapse border border-slate-200 text-sm">
                                                <tbody>
                                                    {displayData.map((row: any[], i: number) => (
                                                        <tr key={i} className={i === 0 ? 'bg-slate-50 font-semibold' : ''}>
                                                            {row.map((cell: any, j: number) => (
                                                                <td key={j} className="border border-slate-200 p-2 text-center text-slate-700">
                                                                    {String(cell ?? '')}
                                                                </td>
                                                            ))}
                                                        </tr>
                                                    ))}
                                                </tbody>
                                            </table>
                                        </>
                                    );
                                })()}
                            </div>
                        )}
                    </div>
                ))}
            </div>
        </div>
    );
};

export default PrintView;
